---
- hosts: all
  become: true
  tasks:
    - name: run command
      command: hostname
      register: output
      - debug: output.stdout_lines
  handlers:
  - name: run update
    apt:
      update_cache: yes
